backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: thumbnail, label: "Featured Image", widget: image, allow_multiple: false }
      - { name: body, label: Body, widget: markdown }
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
  
  - name: book
    label: Book
    folder: src/pages/book
    create: true
    fields:
      - { name: date, label: "Date Started", widget: date }
      - { name: datecomplete, label: "Date Completed", widget: date, required: false }
      - { name: title, label: Title }
      - { name: authorfirst, label: "Author First Name" }
      - { name: authorlast, label: "Author Last Name" }
      - { name: category, label: Category }
      - { name: pages, label: "Pages", widget: number, valueType: "int" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "book" }

  - name: futuretalk
    label: Future Talk
    folder: src/pages/future-talk
    create: true
    fields: 
      - { label: "Layout", name: "layout", widget: "hidden", default: "future-talk" }
      - { name: title, label: "Talk Title" }
      - { name: date, label: "Date", widget: date }
      - { name: eventpage, label: "Event Page", required: false }
      - { name: group, label: 'Group or Event'}
  - name: learning
    label: 'Learning Log'
    folder: src/pages/learningLog
    create: true
    fields: 
      - { label: "Layout", name: "layout", widget: "hidden", default: "learning" }
      - { name: title, label: "Title"}
      - { name: date, label: "Date"}
      - { name: fcc, label: "Free Code Camp: Items Completed", required: false, widget: number}
      - { name: fcc, label: "Free Code Camp: Project Working On", required: false}
      - { name: fcc, label: "Free Code Camp: Notes", required: false, widget: markdown}
      - { name: body, label: "Daily Notes", widget: markdown }

  - name: now
    label: Now 
    folder: src/pages/now
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "now" }
      - { name: title, label: "Title(used for file name only): mm-dd-yy" }
      - { name: date, label: "Date", widget: date }
      - { name: tech1, label: "Technology Focus: 1", widget: string }
      - { name: tech2, label: "Technology Focus: 2", widget: string }
      - { name: tech3, label: "Technology Focus: 3", widget: string }
      - { name: personalprojecttitle, label: "Personal Project Title", widget: string }
      - { name: personalprojectabout, label: "Personal Project About", widget: markdown }
      - { name: jobcompany, label: "Company I Work At", widget: string, default: "Searching" }
      - { name: jobtitle, label: "Job Title", widget: string, default: "Front End Web Developer" }
      - { name: body, label: "General Info", widget: markdown }

  - name: project
    label: Project
    folder: src/pages/project
    create: true
    fields: 
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: techs, label: Techs, widget: list, 
            field: {
              name: tech, 
              label: Tech,  
              widget: relation, 
              collection: tech, 
              searchFields: "name", 
              valueField: "name", 
              displayFields: "name" }
        }
      - { label: "Layout", name: "layout", widget: "hidden", default: "project" }

  - name: talk
    label: Talk
    folder: src/pages/talk
    create: true
    fields: 
      - { label: "Layout", name: "layout", widget: "hidden", default: "talk" }
      - { name: title, label: "Talk Title" }
      - { name: date, label: "Date", widget: date }
      - { name: notistlink, label: "Noti.st Link", required: false  }
      - { name: eventpage, label: "Event Page", required: false }
      - { name: slides, label: "Slides" }
      - { name: coverimage, label: "Image", widget: image, allow_multiple: false}   
      - { name: conference, label: Confernece, widget: boolean, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: tech
    label: Tech
    folder: src/pages/tech
    create: true
    fields: 
      - { name: title, label: Title }
      - { name: icon, label: "Icon", widget: image, allow_multiple: false }
      - { label: "Layout", name: "layout", widget: "hidden", default: "tech" }
  
  - name: uses
    label: Uses 
    folder: src/pages/uses
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "uses" }
      - { name: title, label: "Thing I Use"}
      - { name: date, label: "Date", widget: date }
      - { name: url, label: URL }
      - { name: image, label: "Image or Logo", widget: image, allow_multiple: false }
      - { name: category, label: Category }
      - { name: body, label: Body, widget: markdown }
  
