backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
  - name: tech
    label: Tech
    folder: src/pages/tech
    create: true
    fields: 
      - { name: title, label: Title }
      - {label: "Layout", name: "layout", widget: "hidden", default: "tech"}
  - name: project
    label: Project
    folder: src/pages/project
    create: true
    fields: 
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: techs, label: Techs, widget: list, 
            field: {name: tech, label: Tech,  widget: relation, collection: tech, searchFields: "name", valueField: "name", displayFields: "name" }
        }
      - {label: "Layout", name: "layout", widget: "hidden", default: "project"}
  - name: book
    label: Book
    folder: src/pages/book
    create: true
    fields:
      - { name: date, label: "Date Started", widget: date }
      - { name: datecomplete, label: "Date Completed", widget: date, required: false }
      - { name: title, label: Title }
      - { name: authorfirst, label: "Author First Name" }
      - { name: authorlast, label: "Author Last Name" }
      - { name: category, label: Category }
      - { name: pages, label: "Pages", widget: number, valueType: "int" }
      - {label: "Layout", name: "layout", widget: "hidden", default: "book" }
  - name: now
    label: Now 
    folder: src/pages/now
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "now" }
      - { name: date, label: "Date", widget: date }
      - { name: body, label: Body, widget: markdown }
      - { name: featured, label: featured, widget: boolean }
      - { name: image, label: "Icon", widget: image, allow_multiple: false, required: false }
  - name: uses
    label: Uses 
    folder: src/pages/uses
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "uses" }
      - { name: date, label: "Date", widget: date }
      - { name: image, label: "Image or Logo", widget: image, allow_multiple: false }
      - { name: category, label: Category }
      - { name: body, label: Body, widget: markdown }


      